After instance reboot do another switch to make sure all services start

diff --git a/bin/terraflake b/bin/terraflake
--- a/bin/terraflake
+++ b/bin/terraflake
@@ -19,6 +19,7 @@ shopt -s inherit_errexit failglob
 #  14  couldn't copy derivation closure to node
 #  15  couldn't get system of remote node
 #  100 instance needs reboot to complete
+#  101 instance not reachable after infect
 
 BIN_DIR=$(cd "${BASH_SOURCE[0]%/*}"; pwd)
 export BIN_DIR
@@ -63,7 +64,7 @@ Commands:
     -l|--local            Realize derivation locally
     -b|--bundle           Bundle derivations
     -d|--dry              Upload closure but do not switch to configuration
-    -r|--auto-reboot      Reboot instance if needed (default is to fail instead)
+    -n|--no-reboot        Reboot instance if needed (default is to fail instead)
   secret NAMES..          Copy secrets to remote nodes
     -d|--dry              Check but don't copy
     -f|--force            Force copy
@@ -100,6 +101,11 @@ _par() {
   xargs -L1 -P"$NF_PAR" bash -c "set -eo pipefail;shopt -s inherit_errexit failglob; $([[ -z $NF_DEBUG ]] || echo set -x\;) $1" _ "${@:2}"
 }
 export -f _par
+
+_isgit() {
+  git rev-parse >&2 2>/dev/null
+}
+export -f _isgit
 
 _remote() {
   mapfile -t opts <<<"$SSH_OPTS"
@@ -151,10 +157,10 @@ _confPath() {
 }
 export -f _confPath
 
-_system() {
-  nix eval --impure --raw --expr 'builtins.currentSystem'
-}
-export -f _system
+# _system() {
+#   nix eval --impure --raw --expr 'builtins.currentSystem'
+# }
+# export -f _system
 
 _remoteSystem() {
   local ip="$1"
@@ -168,8 +174,9 @@ export -f _remoteSystem
 _output() {
   local name="$1"
   local expr="${*:2}"
+  # shellcheck disable=SC2086
   nix eval "$NF_FLAKE#nixosConfigurations.$name.config" \
-    --json --apply "$expr"
+    ${_OUTPUT_IMPURE+--impure} --json --apply "$expr"
 }
 export -f _output
 
@@ -315,13 +322,15 @@ _checkConfigurator() {
 export -f _checkConfigurator
 
 _checkUp() {
+  local name="$1"
+  local retries="${2:-3}"
   local ip
 
-  ip=$(_instance "$1" ip)
+  ip=$(_instance "$name" ip)
   echo >&2 "Checking SSH connection..."
-  for i in $(seq 3); do
+  for i in $(seq "$retries"); do
     _remote "$ip" true </dev/null \
-      && return 0 || echo >&2 "Info: SSH connection failed, try $i/3"
+      && return 0 || echo >&2 "Info: SSH connection failed, try $i/$retries"
     sleep 5
   done
   echo >&2 "Error: Couldn't connect over SSH"
@@ -441,7 +450,7 @@ in {
   ];
 }
 EOF
-
+  if _isgit; then git add -N "$confPath"; fi
   echo "$name" "$confPath"
 }
 export -f _initInstance
@@ -460,7 +469,7 @@ export -f _buildInstance
 
 _pushInstance() {
   local localRealize
-  local forceReboot
+  local noReboot
   local op; op="switch"
   local name
   local ip
@@ -471,7 +480,7 @@ _pushInstance() {
     -l|--local) localRealize=1;;
     -b|--bundle) bundleDerivations=1;;
     -d|--dry) op="dry-activate";;
-    -r|--auto-reboot) forceReboot=1;;
+    -n|--no-reboot) noReboot=1;;
     -*) true;; #echo >&2 "Not a recognized push option '$1'"; return 13;;
     *)
       if [ -z "$name" ]; then name="$1"
@@ -557,11 +566,21 @@ EOF
         ;;
       100)
         echo >&2 "Instance needs to reboot to finish configuration"
-        if [[ -n "$forceReboot" ]]; then
+        if [[ -z "$noReboot" ]]; then
           echo >&2 "Rebooting..."
           _remote "$ip" reboot </dev/null || true
+          _checkUp "$name" 5 || {
+            echo >&2 "Couldn't reach instance after reboot"
+            exit 101
+          }
+          _infect "$ip" switch "$op" "$path" || {
+            case "$?" in
+              4) echo >&2 "Warning: Couldn't start all services";;
+              *) return 8;;
+            esac
+          }
         else
-          echo >&2 "Refusing to reboot, use option --auto-reboot or reboot instance manually"
+          echo >&2 "Refusing to reboot because of option --no-reboot, reboot instance manually"
           exit 100
         fi
         ;;
@@ -609,10 +628,12 @@ _init() {
 # CLI commands
 
 init() {
+  local provisioner_file="$NF_DIR/terraform-local.nix"
   mkdir -p "$NF_DIR"
   # Setup provisioner interfaces:
   # TODO: generalize to support multiple interfaces (eg. static JSON file, terraform cloud)
-  cp --no-preserve=all "$LIB_DIR"/provisioners/terraform-local.nix "$NF_DIR/terraform-local.nix"
+  cp --no-preserve=all "$LIB_DIR"/provisioners/terraform-local.nix "$provisioner_file"
+  if _isgit; then git add -N "$provisioner_file"; fi
   _init "$@"
 }
 
@@ -646,8 +667,20 @@ output() {
   [[ -n "${exprs[*]}" ]] \
     || _usage "Missing Nix expression as second argument"
 
-  _output "$name" "{ ... }@config: with config; ${exprs[*]}" \
-    2> >(_ilog "$1") \
+  _OUTPUT_IMPURE=1 _output "$name" "
+    { ... }@config: with config;
+    let
+      pkgs = import <nixpkgs> {};
+      result = (${exprs[*]});
+    in
+      if (builtins.isAttrs result)
+      then
+        pkgs.lib.filterAttrsRecursive
+          (_: v: !(builtins.isFunction v))
+          result
+      else
+        result
+  " 2> >(_ilog "$1") \
     | jq -rM .
 }
 export -f output
