Add SSH connection check and improved logging

diff --git a/bin/terranix b/bin/terranix
--- a/bin/terranix
+++ b/bin/terranix
@@ -9,15 +9,19 @@ set -e -o pipefail
 # - 5  not a valid config closure
 # - 6  no state file found
 # - 7  no deploy file (terranix.nix) found
+# - 8  config push failed
+# - 9  couldn't reach instance
 
 BIN_DIR=$(cd "${BASH_SOURCE[0]%/*}"; pwd)
 LIB_DIR="${BIN_DIR%/*}/lib"
 TN_CONFIGURATOR_PATH="${TN_CONFIGURATOR_PATH-./.terranix/configurators:$LIB_DIR/configurators}"
+TN_SSH_OPTS="-o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
 
 _ilog() { sed "s|^|$1> |" >&2; }
 
 _remote() {
-  ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@"$1" "${@:2}"
+  # shellcheck disable=SC2086 disable=SC2029
+  ssh $TN_SSH_OPTS root@"$1" "${@:2}"
 }
 
 _configuratorPath() {
@@ -39,7 +43,7 @@ _instance() {
 
 _configs() {
   [ -f "./terranix.nix" ] \
-    || { echo >&2 "Error: no deploy file (terranix.nix) found"; return 7; }
+    || { echo >&2 "Error: No deploy file (terranix.nix) found"; return 7; }
   nix-instantiate --eval-only --json -E 'builtins.attrNames (import ./terranix.nix)' \
     | jq -r '.[]'
 }
@@ -48,29 +52,40 @@ _checkInstance() {
   local name
 
   name=$(_instance "$1") || return $?
-  [ -n "$name" ] || { echo >&2 "Error: no instance with name: $1"; return 1; }
+  [ -n "$name" ] || { echo >&2 "Error: No instance with name: $1"; return 1; }
 }
 
 _checkInstances() {
   local names
   local names_
 
-  if [ "$*" ]; then
-    names=("$@")
-  else
-    names_=$(_configs) || return $?
-    mapfile -t names <<<"$names_"
+  if [ -n "$*" ]
+    then names=("$@")
+    else names_=$(_configs) || return $?; mapfile -t names < <(echo "$names_")
   fi
   for i in "${!names[@]}"; do
-    _checkInstance "${names[$i]}" || return $?
-    echo "${names[$i]}"
+    _checkInstance "${names[i]}" || return $?
+    echo "${names[i]}"
   done
 }
 
 _checkConfigurator() {
   [ -f "$(_configuratorPath "$1")" ] || {
-    echo >&2 "Error: no configurator found for provider: $1"; return 3
+    echo >&2 "Error: No configurator found for provider: $1"; return 3
   }
+}
+
+_checkUp() {
+  local ip
+
+  ip=$(_instance "$1" ip)
+  echo >&2 "Checking SSH connection..."
+  for i in $(seq 3); do
+    _remote "$ip" true && return 0 || echo >&2 "Info: SSH connection failed, try $i/3"
+    sleep 5
+  done
+  echo >&2 "Error: Couldn't connect over SSH"
+  return 1
 }
 
 _initInstance() {
@@ -87,9 +102,9 @@ _initInstance() {
   _checkConfigurator "$provider"
 
   ip=$(_instance "$name" ip)
-  confPath=".terranix/configuration-$name.nix"
+  confPath="./.terranix/configuration-$name.nix"
 
-  echo >&2 "Initializing config for: $name"
+  echo >&2 "Initializing config..."
 
   # Get instance specific config
   physical_nix=$(_configure "$provider" "$ip") || return $?
@@ -127,7 +142,7 @@ in {
   };
 }
 EOF
-  echo "$confPath"
+  echo "$name" "$confPath"
 }
 
 _buildInstance() {
@@ -135,12 +150,11 @@ _buildInstance() {
   _checkInstance "$name"
   local confPath="./.terranix/configuration-$name.nix"
 
-  echo >&2 "Building config for: $name"
+  echo >&2 "Building config..."
 
   # Build config
   nix-build --no-out-link '<nixpkgs/nixos>' -A system \
-    --arg configuration "$confPath" \
-    2> >(_ilog "$name")
+    --arg configuration "$confPath"
 }
 
 _pushInstance() {
@@ -154,42 +168,42 @@ _pushInstance() {
   ip=$(_instance "$name" ip)
 
   path="$2"
-  [ -e "$path" ] || { echo >&2 "Error: not a valid config closure: $path"; return 5; }
+  [ -e "$path" ] || { echo >&2 "Error: Not a valid config closure: $path"; return 5; }
 
-  echo >&2 "Pushing config to: $name"
+  echo >&2 "Pushing config..."
 
   # Install Nix if not already installed
-  _infect "$ip" sourceNix \
-    2> >(_ilog "$name")
+  _infect "$ip" sourceNix
 
   # Push config closure to instance
-  NIX_SSHOPTS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no PATH=/root/.nix-profile/bin:\$PATH" \
-    nix-copy-closure --to root@"$ip" "$path" \
-    2> >(_ilog "$name")
+  NIX_SSHOPTS="$TN_SSH_OPTS PATH=/root/.nix-profile/bin:\$PATH" \
+    nix-copy-closure --to root@"$ip" "$path"
 
   # Install config and infect instance with NixOS if not already
-  { _infect "$ip" switch "$path" \
-    || {
-      ecode="$?"
-      if [ "$ecode" == 100 ]; then
-        echo -n >&2 "Rebooting..."
+  _infect "$ip" switch "$path" || {
+    case "$?" in
+      100)
+        echo >&2 "Rebooting..."
         _remote "$ip" reboot || true
-        sleep 2
-        _remote "$ip" true
-        echo >&2 " done"
-      else
-        return $ecode
-      fi
-    }
-  } 2> >(_ilog "$name")
+        ;;
+      4)
+        echo >&2 "Warning: Couldn't start all services"
+        ;;
+      *)
+        return 8
+        ;;
+    esac
+  }
 }
 
 _init() {
   local instances
 
   instances=$(_checkInstances) || return $?
+  check
   while read -r name; do
-    _initInstance "$name"
+    _initInstance "$name" \
+      2> >(_ilog "$name")
   done <<<"$instances"
 }
 
@@ -218,7 +232,7 @@ EOF
 
 initFromJSON() {
   [ -f ./terranix-input.json ] \
-    || { echo >&2 "Error: couldn't find input JSON at $PWD/terranix-input.json"; return 6; }
+    || { echo >&2 "Error: Couldn't find input JSON at $PWD/terranix-input.json"; return 6; }
   mkdir -p .terranix
   cat > .terranix/input-transform.nix <<EOF
 { lib, ... }: lib.importJSON ../terranix-input.json;
@@ -229,11 +243,25 @@ EOF
 # shellcheck disable=SC2120
 state() {
   [ -f ./.terranix/input-transform.nix ] \
-    || { echo >&2 "Error: couldn't find input transform, try running: terranix init"; return 6; }
+    || { echo >&2 "Error: Couldn't find input transform, try running: terranix init"; return 6; }
   nix-instantiate --eval-only --strict --json \
     -E 'with import <nixpkgs> {};import ./.terranix/input-transform.nix {inherit lib;}' \
     | jq -rM ".$1 // \"\"" \
-    || { echo >&2 "Error: input transform failed"; return 6; }
+    || { echo >&2 "Error: Input transform failed"; return 6; }
+}
+
+check() {
+  local instances
+  local ecode; ecode=0
+
+  instances=$(_checkInstances "$@") || return $?
+  while read -r name; do
+    _checkUp "$name" \
+      2> >(_ilog "$name") \
+      || { ecode=9; continue; }
+  done <<<"$instances"
+  [ "$ecode" == 0 ] || echo >&2 "Error: Couldn't reach all instance"
+  return $ecode
 }
 
 build() {
@@ -242,10 +270,11 @@ build() {
 
   instances=$(_checkInstances "$@") || return $?
   while read -r name; do
-    path=$(_buildInstance "$name") || {
-      echo >&2 "Error: failed to build config for: $name"; return 4
-    }
-    echo "{\"name\":\"$name\",\"path\":\"$path\"}"
+    { path=$(_buildInstance "$name") || {
+        echo >&2 "Error: Failed to build config"; return 4
+      }
+    } 2> >(_ilog "$name")
+    echo "$name" "$path"
   done <<<"$instances"
 }
 
@@ -255,14 +284,14 @@ push() {
   local buildOutput
 
   buildOutput=$(build "$@") || return $?
-  while read -r buildInfo; do
-    name=$(jq -r .name <<<"$buildInfo")
-    path=$(jq -r .path <<<"$buildInfo")
-    # If exit code is 4 keep pushing
-    _pushInstance "$name" "$path" || [ "$?" == 4 ]
+  check "$@"
+  while read -r name path; do
+    _pushInstance "$name" "$path" \
+      2> >(_ilog "$name")
   done <<<"$buildOutput"
+  check "$@"
 }
 
 trap 'trap - TERM; kill $$' TERM
 
-[ -z "$*" ] || "${1#_}" "${@:2}"
+[ -z "$*" ] || "${1#_}" "${@:2}" && echo >&2 "Done!"
